"""auto update

Revision ID: 51fd35b0ff51
Revises: b3e081c6fc3a
Create Date: 2026-03-30 02:21:03.132657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fd35b0ff51'
down_revision: Union[str, Sequence[str], None] = 'b3e081c6fc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('wallet_address', sa.String(), nullable=True))
    op.add_column('deposits', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('deposits', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('deposits', 'stripe_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('stripe_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('deposits', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('deposits', 'notes')
    op.drop_column('deposits', 'wallet_address')
    # ### end Alembic commands ###