"""auto update

Revision ID: 828588f8298a
Revises: 51fd35b0ff51
Create Date: 2026-04-03 14:30:19.163359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828588f8298a'
down_revision: Union[str, Sequence[str], None] = '51fd35b0ff51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('executed_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('total_fees', sa.String(), nullable=True),
    sa.Column('last_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_tasks_id'), 'expert_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_tasks_id'), table_name='expert_tasks')
    op.drop_table('expert_tasks')
    # ### end Alembic commands ###