"""auto update

Revision ID: 95ffda89e3b6
Revises: ee3d0fc3a0bb
Create Date: 2026-04-29 01:33:44.367610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95ffda89e3b6'
down_revision: Union[str, Sequence[str], None] = 'ee3d0fc3a0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_admins_id'), 'sub_admins', ['id'], unique=False)
    op.add_column('expert_tasks', sa.Column('from_currency', sa.String(), nullable=False))
    op.add_column('expert_tasks', sa.Column('to_currency', sa.String(), nullable=False))
    op.add_column('expert_tasks', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('expert_tasks', sa.Column('executed_count', sa.Integer(), nullable=True))
    op.add_column('expert_tasks', sa.Column('skipped_count', sa.Integer(), nullable=True))
    op.add_column('expert_tasks', sa.Column('total_fees', sa.String(), nullable=True))
    op.add_column('expert_tasks', sa.Column('last_rate', sa.Float(), nullable=True))
    op.drop_column('expert_tasks', 'priority')
    op.drop_column('expert_tasks', 'title')
    op.drop_column('expert_tasks', 'due_date')
    op.drop_column('expert_tasks', 'description')
    op.drop_column('expert_tasks', 'result')
    op.drop_column('expert_tasks', 'assigned_to')
    op.drop_column('expert_tasks', 'task_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_tasks', sa.Column('task_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('expert_tasks', sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('expert_tasks', sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('expert_tasks', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('expert_tasks', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('expert_tasks', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('expert_tasks', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expert_tasks', 'last_rate')
    op.drop_column('expert_tasks', 'total_fees')
    op.drop_column('expert_tasks', 'skipped_count')
    op.drop_column('expert_tasks', 'executed_count')
    op.drop_column('expert_tasks', 'amount')
    op.drop_column('expert_tasks', 'to_currency')
    op.drop_column('expert_tasks', 'from_currency')
    op.drop_index(op.f('ix_sub_admins_id'), table_name='sub_admins')
    op.drop_table('sub_admins')
    # ### end Alembic commands ###